version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: simple-payment
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data
volumes:
  postgresql:
